### PR TITLE
change libtiff4-dev to libtiff5-dev

### PR DESCRIPTION
**Pull request by yilkalargaw**

### CODE REVIEW

**Comment by yilkalargaw** [comment]
still doesn't solve the issue with libtiff I thought it would but may be someone could help?

**Comment by iqbalansari** [comment]
Hi @yilkalargaw,

The change looks good, the test were failing because if seems that `libgnutls28-dev` is now a mandatory requirement.

Also do not worry about the test failure on Emacs v24.5 and Emacs v25.1, one of the tests does not work as expected on these versions (I will most probably stop supporting these versions)  

I am re-opening this PR, since the fix seems to be correct. Can you add `libgnutls28-dev` to the list of packages installed?

Thanks

**Comment by yilkalargaw** [comment]
Yep adding llibgnutls28-dev got the tests passing 26.2. Thanks for the help.

**Comment by iqbalansari** [comment]
Cool thanks a lot @yilkalargaw, merged!

**Pull request merged**
