### PR TITLE
add OpenMoji license to README

### PR DESCRIPTION
**Pull request by DivineDominion**
follow up to #81

### CODE REVIEW

**Comment by iqbalansari** [comment]
Thanks again @DivineDominion

**Comment by DivineDominion** [comment]
👍 were you able to figure out what's up with the hashes @iqbalansari? (Are you computing them with a different algorithm?)

**Comment by iqbalansari** [comment]
Yes, actually the file that you were computing the hashes of (`emojione-v2` was from old version)

**Comment by DivineDominion** [comment]
Phew, ok, good to hear things are working then.

**Pull request merged**
