### PR TITLE
add OpenMoji v13.0

### PR DESCRIPTION
**Pull request by DivineDominion**
Source https://github.com/hfg-gmuend/openmoji

[License](https://github.com/hfg-gmuend/openmoji/blob/master/LICENSE.txt): Attribution-ShareAlike 4.0 International

Examples in modus-* themes:

image
image

I used the 72x72 PNG export from OpenMoji. The emojione PNGs always look blurry with my settings, even on non-retina. The screenshots above at regular pixel density look great, I think. And on retina screens, it's even nicer.

### CODE REVIEW

**Comment by iqbalansari** [comment]
This is great, thanks a lot @DivineDominion for the contribution, I will verify the issue with SHA256 you mentioned in the other PR

**Comment by iqbalansari** [comment]
Hey @DivineDominion I am not sure of the licensing requirements, could you also please update the README and add attribution for the OpenMoji. See https://github.com/iqbalansari/emacs-emojify#licence

**Comment by iqbalansari** [comment]
I see that it is a requirement (https://github.com/hfg-gmuend/openmoji#attribution-requirements)

**Comment by DivineDominion** [comment]
Added the license in #83! Didn't notice that there was a section, too, sorry :)

**Comment by DivineDominion** [comment]
@iqbalansari By the way, they do also have an extensive data folder with a JSON with all emoji

https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/data/openmoji.json

Excerpt:

```
  {
    "emoji": "😃",
    "hexcode": "1F603",
    "group": "smileys-emotion",
    "subgroups": "face-smiling",
    "annotation": "grinning face with big eyes",
    "tags": "face, mouth, open, smile",
    "openmoji_tags": "eyes, teeth",
    "openmoji_author": "Emily Jäger",
    "openmoji_date": "2018-04-18",
    "skintone": "",
    "skintone_combination": "",
    "skintone_base_emoji": "",
    "skintone_base_hexcode": "",
    "unicode": 0.6,
    "order": 2
  },
```

maybe it would make sense to rely on their data to generate `emacs-emojify` data as well? Then you and contributors can automate the process a bit more, perhaps. (I actually have no clue if that helps in the workflow. If that would make things easier, I'd suggest you open an enhancement issue; then I could see if I can help, too, at some point.)

**Comment by iqbalansari** [comment]
That makes sense. I have been wanting to automate (or at the very least document) the process of adding new emoji sets. Will take a look at openmoji data. Thanks a lot!

**Pull request merged**
